### ISSUE TITLE
What license is this code available under?

### ISSUE THREAD

**Issue by claes** [YuukanOO/rtv#1]
Can it be used under an open source license, and if so, which one?

**Comment by YuukanOO** [comment]
The "Do what you want with it licence". That was an experiment so no restriction at all.

**Comment by claes** [comment]
That's cool! For your information, I reused this code in a MQTT bridge, so it is possible to control a TV using that protocol

https://github.com/claes/samsung-mqtt

**Comment by YuukanOO** [comment]
Thanks for sharing ;)
